# Generated by Django 4.0.10 on 2023-09-05 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('affiche', models.ImageField(upload_to='evenement_affiches/')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('entraineur', 'Entraîneur'), ('benevole', 'Bénévole')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('installation', 'Installation'), ('equipement', 'Équipement'), ('stock', 'Stock')], max_length=20)),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportClub.membre')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportClub.ressource')),
            ],
        ),
        migrations.CreateModel(
            name='MembreEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportClub.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportClub.membre')),
            ],
        ),
        migrations.CreateModel(
            name='MembreActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportClub.activite')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportClub.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField()),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportClub.membre')),
            ],
        ),
    ]
