# Generated by Django 4.0.10 on 2023-09-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportClub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='affiche',
            field=models.ImageField(default='full-shot-woman-doing-sport.jpg', upload_to='activite_affiches/'),
        ),
    ]
