# Generated by Django 4.0.10 on 2023-09-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportClub', '0004_alter_activite_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='equipement',
            field=models.ImageField(default='poids-haltere-fonte.jpg', upload_to='equipement_photo/'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='lieu',
            field=models.CharField(default='Club VitalFit ,12 Rue des Palmiers, Quartier des Fleurs, Casablanca, Maroc', max_length=100),
        ),
    ]
