# Generated by Django 4.0.10 on 2023-09-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportClub', '0005_ressource_equipement_alter_activite_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(default='XXXXX@gmail.com', max_length=254),
        ),
    ]
