# Generated by Django 4.0.10 on 2023-09-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportClub', '0006_membre_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
